# Generated by Django 4.1.6 on 2023-02-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anskey',
            old_name='givenAns',
            new_name='givenAns1',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='ansKey',
            new_name='ansKey1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='srno',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='totalMarks',
        ),
        migrations.AddField(
            model_name='anskey',
            name='givenAns2',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='anskey',
            name='givenAns3',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='ansKey2',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='ansKey3',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='ifCorrect',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='questions',
            name='ifIncorrect',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='result',
            name='marks',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
