# Generated by Django 4.1.6 on 2023-02-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0002_rename_givenans_anskey_givenans1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anskey',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
