# Generated by Django 4.1.6 on 2023-02-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0007_alter_anskey_givenans1'),
    ]

    operations = [
        migrations.AddField(
            model_name='anskey',
            name='correctAns',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='anskey',
            name='scored',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
