# Generated by Django 4.1.7 on 2023-03-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0008_anskey_correctans_anskey_scored'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anskey',
            name='givenAns2',
        ),
        migrations.RemoveField(
            model_name='anskey',
            name='givenAns3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='ansKey2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='ansKey3',
        ),
        migrations.AlterField(
            model_name='questions',
            name='ansKey1',
            field=models.TextField(),
        ),
    ]
