# Generated by Django 4.1.7 on 2023-03-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0009_remove_anskey_givenans2_remove_anskey_givenans3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anskey',
            name='correctAns',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='anskey',
            name='givenAns1',
            field=models.TextField(default=None, null=True),
        ),
    ]
